services:
  ade:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ade
    ports:
      - "${PORT:-6969}:6969"
    volumes:
      # Mount ADE
      - ./app:/app

      # Mount Data
      - ./data:/data

      # Mount Projects
      - ./projects:/projects
    env_file:
      - .env
    restart: unless-stopped
